### ISSUE TITLE
Infinite loading in sample-link-ui

### ISSUE THREAD

**Issue by ZiggerZZ** [tink-ab/tink-link-android#30]
Hello,

I followed the readme in Tink Link UI Sample to add `link-demo://tink` to the list of redirect URIs under my app's settings and specify the CLIENT_ID.

The app launches successfully, however, when I click on the button "Launch Tink Link", I get a never ending loading screen.
<img width="381" alt="Screenshot 2022-01-14 at 14 32 47" src="https://user-images.githubusercontent.com/13183693/149532571-5147f20b-1a04-463e-8298-c0a04373b761.png">

Any ideas on how to fix it?

**Comment by ShounakCy** [comment]
Hi, did you find a resolution to this? I am facing the same issue.

**Comment by JonathanPeterCole** [comment]
Just run into this issue today, in my testing it seems to only be happening on Android emulators. Clean booting the emulator seems to resolve the issue, at least temporarily.

There does seem to be an issue with some errors not being handled correctly however. When starting Tink Link with an invalid authorization code, a code 16 (unauthorized) API response appears in the logs, but the UI will get stuck on the loading spinner rather than returning `TinkLinkUiActivity.RESULT_FAILURE`.

**Comment by muhammad-umair-shafique** [comment]
This issue is not valid with TinkLink 2.0.

**Comment by muhammad-umair-shafique** [comment]
Closing it because this issue is not valid with TinkLink 2.0.
